name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get version number
        id: tag_number
        run: |
          CURRENT_TAG=$(git tag --sort=-creatordate | sed -n 1p)
          DOCKERHUB_TAG="${CURRENT_TAG//v/}"
          echo "::set-output name=dh_tag::${DOCKERHUB_TAG}"
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tbsmcd/nlp_pytorch
          tags: |
            tbsmcd/nlp_pytorch:latest
            tbsmcd/nlp_pytorch:${{steps.tag_number.outputs.dh_tag}}