name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get version number
        run: |
          ver=${GITHUB_REF:10}
          ver="${ver//v//}"
          echo $ver
#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: tbsmcd/nlp_pytorch
#          tag_with_ref: true